#!/usr/bin/env Rscript
# vi: ft=R
library(RUnit, quietly = TRUE)
args <- commandArgs(trailingOnly = F)
script.path <- sub("--file=","",args[grep("--file",args)])
source(file.path(dirname(script.path), '..', 'chem.R'), chdir = TRUE)

#################
# TEST LOAD SDF #
#################

test.load.sdf <- function() {

	library(rJava)

	# Bad file
	checkTrue(is.null(load.sdf('toto.sdf')))

	# Read file
	file <- file.path(dirname(script.path), 'files', 'results_2_MSMS.txt-chemspider.sdf')
	mols <- load.sdf(file)
	checkTrue( ! is.null(mols))
	checkEquals(length(mols$struct), nrow(mols$info))

	# Check InChIs
	if ('InChI' %in% colnames(mols$info))
		for (i in seq(mols$struct)) {
			inchi <- get.inchi(mols$struct[[i]])
			checkEquals(inchi, mols$info[i, 'InChI'])
		}
}

##################
# TEST GET INCHI #
##################

test.get.inchi <- function() {
	file <- file.path(dirname(script.path), 'files', 'results_2_MSMS.txt-chemspider.sdf')
	mols <- load.sdf(file)
		for (i in seq(mols$struct))
			checkTrue( ! is.na(get.inchi(mols$struct[[i]])))
}

########
# MAIN #
########

test.get.inchi()
test.load.sdf()
