#!/usr/bin/env Rscript
# vi: ft=R
library('methods') # needed by RUnit
library(RUnit)
args <- commandArgs(trailingOnly = F)
script_path <- sub("--file=","",args[grep("--file",args)])
source(file.path(dirname(script_path), '..', 'dfhlp.R'), chdir = TRUE)

#######################
# TEST REMOVE NA ROWS #
#######################

test.remove.na.rows <- function() {

	# Data frame without NA rows
	data_frames <- list(data.frame(), data.frame(c(1)), data.frame(c(1,4)), data.frame(c(4,2),c(6.3)), data.frame(c(5,NA), c(7,8)), data.frame(c(NA,2), c(5,NA)))
	for (t in data_frames)
		checkIdentical(remove.na.rows(t), t)

	# Data frame with NA rows
	#                   INPUT                           OUTPUT
	data_frames <- list(data.frame(a = c(NA_integer_)),          data.frame(a = integer()),
	                    data.frame(a = c(NA,7), b = c(NA,1)),   data.frame(a = c(7), b = c(1), row.names = c(2))
	                   )
	i <- 1
	while (i < length(data_frames)) {
		a <- data_frames[[i]]
		b <- remove.na.rows(data_frames[[i]])
		c <- data_frames[[i+1]]
		print(a)
		print(class(b))
		print(mode(b))
		print(typeof(b))
		print(attributes(b))
		print(b)
		print(class(c))
		print(mode(c))
		print(typeof(c))
		print(attributes(c))
		print(c)
		checkIdentical(b, c)
#		print(data_frames[[i]])
#		print(remove.na.rows(data_frames[[i]]))
#		print(data_frames[[i+1]])
#checkIdentical(remove.na.rows(data_frames[[i]]), data_frames[[i+1]])
		i <- i + 2
	}
}

########
# MAIN #
########

test.remove.na.rows()
