#!/usr/bin/env Rscript
# vi: ft=R
library('methods') # needed by RUnit
library(RUnit)
args <- commandArgs(trailingOnly = F)
script_path <- sub("--file=","",args[grep("--file",args)])
source(file.path(dirname(script_path), '..', 'dfhlp.R'), chdir = TRUE)

#######################
# TEST REMOVE NA ROWS #
#######################

test.remove.na.rows <- function() {

	# Data frame without NA rows
	data_frames <- list(data.frame(), data.frame(c(1)), data.frame(c(1,4)), data.frame(c(4,2),c(6.3)), data.frame(c(5,NA), c(7,8)), data.frame(c(NA,2), c(5,NA)))
	for (t in data_frames)
		checkIdentical(remove.na.rows(t), t)

	# Data frame with NA rows
	#                   INPUT                           OUTPUT
	data_frames <- list(data.frame(a = c(NA_integer_)),          data.frame(a = integer()),
	                    data.frame(a = c(7,NA), b = c(5,NA)),   data.frame(a = c(7), b = c(5)),
	                    data.frame(a = c(NA,7), b = c(NA,1)),   data.frame(a = c(7), b = c(1), row.names = as.integer(c('2')))
	                   )
	i <- 1
	while (i < length(data_frames)) {
		checkIdentical(remove.na.rows(data_frames[[i]]), data_frames[[i+1]])
		i <- i + 2
	}
}

##########################
# TEST MOVE COLUMNS LAST #
##########################

test.move.col.last <- function() {

	# 2 cols
	x <- data.frame(a=c(1,4),b=c(5,16))
	y <- df.move.col.last(x, 'a')
	checkIdentical(colnames(y), c('b', 'a'))

	# 3 cols
	x <- data.frame(a=c(1,4),b=c(5,16), c=c(56,13))
	y <- df.move.col.last(x, 'b')
	checkIdentical(colnames(y), c('a', 'c', 'b'))
}

###########################
# TEST MOVE COLUMNS FIRST #
###########################

test.move.col.first <- function() {

	# 2 cols
	x <- data.frame(a=c(1,4),b=c(5,16))
	y <- df.move.col.first(x, 'b')
	checkIdentical(colnames(y), c('b', 'a'))

	# 3 cols
	x <- data.frame(a=c(1,4),b=c(5,16),c=c(57,123))
	y <- df.move.col.first(x, 'b')
	checkIdentical(colnames(y), c('b', 'a', 'c'))
}

########
# MAIN #
########

test.remove.na.rows()
test.move.col.first()
test.move.col.last()
